name: Clean Trivy Scan V3

on:
  workflow_dispatch:

jobs:
  call-trivy:
    uses: kenji-mine/test_dashboard/.github/workflows/trivy-template.yml@main
    with:
      sbom_path: 'sbom/sbom.json'
    secrets: inherit
